### ISSUE TITLE
 reading EKS Cluster (eks-relay): couldn't find resource

### ISSUE THREAD

**Issue by 2019jack** [ObolNetwork/terraform-charon-relay#8]
execute command: `terraform apply`

error:
```
Error: reading EKS Cluster (eks-relay): couldn't find resource
│
│   with data.aws_eks_cluster.this,
│   on versions.tf line 27, in data "aws_eks_cluster" "this":
│   27: data "aws_eks_cluster" "this" {
```

 Line 27 of my task versions.tf file needs to be modified? Have any suggestions?

**Comment by aly-obol** [comment]
@2019jack you need a working EKS cluster in the same AWS account, then this `data "aws_eks_cluster" "this"` block will retrieve the cluster state.
